
import ContactSection from "@/components/ContactSection";
import DiscountStrip from "@/components/DiscountStrip";
import Faq from "@/components/faqSection/Faq";
import Footer from "@/components/footer/Footer";
import MiniFooter from "@/components/footer/MiniFooter";
import LandingPage from "@/components/landingPage/LandingPage";
import OurClients from "@/components/ourClient/OurClients";
import OurExpertiseSection from "@/components/OurExpertiseSection";
import TestimonialSection from "@/components/testimonialSection/TestimonialSection";
import Head from "next/head";



export default function Home() {
  return (
    <div className="home-container">
      <Head>
        <title>Launch Wise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DiscountStrip />
      <LandingPage/>
      <OurExpertiseSection />
      <ContactSection />
      <OurClients />
      <TestimonialSection />
      <Faq />
      <Footer />
      <MiniFooter />
    </div>
  );
}
